CREATE TABLE authors (
                         id bigserial,
                         full_name varchar(255),
                         PRIMARY KEY (id)
);

CREATE TABLE genres (
                        id bigserial,
                        name varchar(255),
                        PRIMARY KEY (id)
);

CREATE TABLE books (
                       id bigserial,
                       title varchar(255),
                       author_id bigint REFERENCES authors (id) ON DELETE CASCADE,
                       adult_only boolean,
                       PRIMARY KEY (id)
);

CREATE TABLE books_genres (
                              book_id bigint REFERENCES books(id) ON DELETE CASCADE,
                              genre_id bigint REFERENCES genres(id) ON DELETE CASCADE,
                              PRIMARY KEY (book_id, genre_id)
);

CREATE TABLE comments (
                       id bigserial,
                       text varchar(255),
                       book_id bigint REFERENCES books (id) ON DELETE CASCADE,
                       PRIMARY KEY (id)
);

CREATE TABLE users (
    id bigserial,
    username varchar(255),
    password varchar(255),
    age integer,
    PRIMARY KEY (id)
);

CREATE TABLE roles (
    id bigserial,
    name varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE user_roles (
    user_id bigint REFERENCES users(id) ON DELETE CASCADE,
    role_id bigint REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY(user_id, role_id)
);

--
-- ACL
--

CREATE TABLE IF NOT EXISTS acl_sid (
    id BIGINT generated by default as identity NOT NULL PRIMARY KEY,
    principal BOOLEAN NOT NULL,
    sid VARCHAR(100) NOT NULL,
    UNIQUE (sid, principal)
    );


CREATE TABLE IF NOT EXISTS acl_class (
    id BIGINT generated by default as identity NOT NULL PRIMARY KEY,
    class VARCHAR(255) NOT NULL,
    UNIQUE (class)
    );


CREATE TABLE IF NOT EXISTS acl_entry (
    id BIGINT generated by default as identity NOT NULL PRIMARY KEY,
    acl_object_identity BIGINT NOT NULL,
    ace_order INT NOT NULL,
    sid BIGINT NOT NULL,
    mask INT NOT NULL,
    granting BOOLEAN NOT NULL,
    audit_success BOOLEAN NOT NULL,
    audit_failure BOOLEAN NOT NULL,
    UNIQUE (acl_object_identity, ace_order)
    );


CREATE TABLE IF NOT EXISTS acl_object_identity (
     id BIGINT generated by default as identity NOT NULL PRIMARY KEY,
     object_id_class BIGINT NOT NULL,
     object_id_identity BIGINT NOT NULL,
     parent_object BIGINT DEFAULT NULL,
     owner_sid BIGINT DEFAULT NULL,
     entries_inheriting BOOLEAN NOT NULL,
     UNIQUE (object_id_class, object_id_identity)
    );


ALTER TABLE acl_entry
    ADD FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id);

ALTER TABLE acl_entry
    ADD FOREIGN KEY (sid) REFERENCES acl_sid(id);

ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (parent_object) REFERENCES acl_object_identity(id);

ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (object_id_class) REFERENCES acl_class(id);

ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (owner_sid) REFERENCES acl_sid(id);
